---
name: events
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  dotted_border: ^2.0.0
  barcode_widget: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/images/onboarding/
  fonts:
  - family: Lacquer
    fonts:
    - asset: assets/fonts/Lacquer-Regular.ttf
      weight: 700
  - family: Nunito
    fonts:
    - asset: assets/fonts/Nunito-Light.ttf
      weight: 300
  - family: Lato
    fonts:
    - asset: assets/fonts/Lato-Bold.ttf
      weight: 500
